# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://claude.formanek.co.za/'
baseurl: ''
title: 'Claude Formanek'
description: 'Personal Portfolio Website'
permalink: pretty
logo: "/assets/logos/claude_formanek_logo_250.png"

# Pagination
paginate: 5
paginate_path: posts/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Posts
  url: /posts/
- title: Categories
  url: /categories/

# Footer nav
navigation_footer:
# - title: Back to top
#   url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "A collection of projects, talks and events I have been a part of."
    feature_text: 
    feature_image: "/assets/images/cape_town_mountain.jpeg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  32: '/assets/logos/CF_logo_32.png'
  96: '/assets/logos/CF_logo_96.png'
  120: '/assets/logos/CF_logo_120.png'
  144: '/assets/logos/CF_logo_144.png'
  180: '/assets/logos/CF_logo_180.png'
