# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://claude.formanek.co.za/'
baseurl: ''
title: 'Claude Formanek'
description: 'Personal Portfolio Website'
permalink: pretty
logo: "assets/logos/claude_formanek_logo.png"

# Pagination
paginate: 5
paginate_path: posts/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
# - title: Back to top
#   url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My Posts"
    feature_text: 
    feature_image: "/assets/images/cape_town_mountian.jpeg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
